namespace RecordFlow.Core.Workspaces;

/// <summary>
/// Temporary working record created from one CSV row. Relationship maintained by the workflow:
/// CSV row → WorkingRecord → Share (secure link) → recipient response.
/// </summary>
public sealed class WorkingRecord
{
    /// <summary>Random, unguessable key used in URLs. Only valid inside the owner's workspace.</summary>
    public string Key { get; set; } = string.Empty;

    public int RowNumber { get; set; }
    public string ContactId { get; set; } = string.Empty;
    public bool ContactIdGenerated { get; set; }

    /// <summary>Generated by the application when the record is created (dashboard Date/Time).</summary>
    public DateTimeOffset CreatedAtUtc { get; set; }

    /// <summary>"Y", "N" or null.</summary>
    public string? Response { get; set; }

    /// <summary>Original CSV cells (header → value). Purged when the record is closed.</summary>
    public Dictionary<string, string> CsvValues { get; set; } = [];

    /// <summary>Values the user typed into editable admin columns (slot → value).</summary>
    public Dictionary<int, string> AdminColumnValues { get; set; } = [];

    /// <summary>Admin column values frozen when the record was closed (slot → value).</summary>
    public Dictionary<int, string>? ClosedAdminColumnValues { get; set; }

    public RecordStatus Status { get; set; } = RecordStatus.Imported;

    /// <summary>Generated form. Null until "Generate Form" runs after payment.</summary>
    public List<WorkingField>? Fields { get; set; }

    public CheckoutDetails? Checkout { get; set; }
    public Guid? OrderPublicId { get; set; }
    public string? OrderNumber { get; set; }

    public ShareInfo? Share { get; set; }
    public DateTimeOffset? RecipientSubmittedAtUtc { get; set; }
    public string? RecipientName { get; set; }

    public DateTimeOffset? ConfirmedAtUtc { get; set; }
    public string? ConfirmedBy { get; set; }
    public DateTimeOffset? ClosedAtUtc { get; set; }
    public string? ConfirmationNumber { get; set; }

    /// <summary>Display name snapshot, kept after CSV values are purged.</summary>
    public string? StoreName { get; set; }

    public bool IsClosed => Status == RecordStatus.Verified;
    public bool IsPaidOrLater => Status >= RecordStatus.Paid;

    public string? GetCsvValue(string header) =>
        CsvValues.TryGetValue(header, out var v) && !string.IsNullOrWhiteSpace(v) ? v : null;

    public WorkingField? FindField(string key) =>
        Fields?.FirstOrDefault(f => string.Equals(f.Key, key, StringComparison.Ordinal));

    public int MissingRequiredCount => Fields?.Count(f => f.IsRequired && f.IsMissing) ?? 0;
    public int MissingCount => Fields?.Count(f => f.IsMissing) ?? 0;
}

public sealed class WorkingField
{
    public string Key { get; set; } = string.Empty;
    public string Label { get; set; } = string.Empty;
    public FormSection Section { get; set; }
    public FieldType FieldType { get; set; }
    public bool IsRequired { get; set; }
    public bool RecipientEditable { get; set; }
    public string? HelpText { get; set; }
    public int MaxLength { get; set; } = 250;
    public List<string> Options { get; set; } = [];
    public int Order { get; set; }

    /// <summary>The CSV value this field started with (null when the CSV had none).</summary>
    public string? CsvValue { get; set; }

    public string? Value { get; set; }
    public FieldSource Source { get; set; }
    public DateTimeOffset? UpdatedAtUtc { get; set; }
    public string? UpdatedBy { get; set; }

    public bool IsMissing => string.IsNullOrWhiteSpace(Value);
    public bool ChangedFromCsv => !string.Equals(CsvValue ?? "", Value ?? "", StringComparison.Ordinal);
}

public sealed class CheckoutDetails
{
    public string BillingName { get; set; } = string.Empty;
    public string BillingEmail { get; set; } = string.Empty;
    public string AddressLine1 { get; set; } = string.Empty;
    public string? AddressLine2 { get; set; }
    public string City { get; set; } = string.Empty;
    public string State { get; set; } = string.Empty;
    public string ZipCode { get; set; } = string.Empty;
    public PaymentMethodKind PaymentMethod { get; set; }
}

public sealed class ShareInfo
{
    /// <summary>Raw token, kept only inside the encrypted workspace so the link can be re-displayed.</summary>
    public string Token { get; set; } = string.Empty;

    /// <summary>SHA-256 of the token; the cache index key for lookups.</summary>
    public string TokenHash { get; set; } = string.Empty;

    public DateTimeOffset CreatedAtUtc { get; set; }
    public DateTimeOffset ExpiresAtUtc { get; set; }
    public DateTimeOffset? LastOpenedAtUtc { get; set; }

    /// <summary>Each link accepts one recipient submission; a new link is needed for further changes.</summary>
    public DateTimeOffset? SubmittedAtUtc { get; set; }

    /// <summary>Channels/addresses the link was sent through (for the owner's reference only).</summary>
    public List<string> SentTo { get; set; } = [];

    public bool IsUsable(DateTimeOffset now) => SubmittedAtUtc is null && ExpiresAtUtc > now;
}
